baseURL = "gogole.com"
languageCode = "fa-ir"
title = "ESP Relay"
theme = "vanilla-bootstrap-hugo-theme"
#googleAnalytics = "UA-123456789-1"

# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
# pygmentsStyle = "pygments"

#[permalinks]
#  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Settings"
    pre = "settings"
    url = "/settings"
    weight = 2
  [[menu.nav]]
    name = "About"
    pre = "info"
    url = "/about"
    weight = 4

[params]
  includeBootstrapJs = true
  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = ""
  footerText = "Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)"
  hideFooter = false
